apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: db_root_password
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: db_user
            - name: MYSQL_PASSWORD
              value: db_password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc